cmdset.o: cmdset.cc ../ddconfig.h cmdlexcl.h ../i_string.h ../ddconfig.h \
  ../utils.h ../stypes.h ../globals.h ../appcl.h ../pobjcl.h ../pobjt.h \
  ../eventcl.h ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../sim.src/simcl.h cmdsetcl.h \
  cmdutil.h ../sim.src/uccl.h
command.o: command.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
  commandcl.h ../pobjcl.h ../pobjt.h ../eventcl.h newcmdcl.h ../appcl.h \
  ../pobjcl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h ../pobjcl.h \
  ../stypes.h ../sim.src/simcl.h newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h
cmdutil.o: cmdutil.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
  ../stypes.h ../globals.h ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h \
  ../eventcl.h ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../sim.src/uccl.h cmdutil.h
syntax.o: syntax.cc syntaxcl.h
get.o: get.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../utils.h \
  ../stypes.h ../sim.src/simcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  newcmdcl.h ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../optioncl.h cmdsetcl.h \
  getcl.h cmdutil.h ../sim.src/uccl.h
set.o: set.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../errorcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../stypes.h ../sim.src/simcl.h \
  ../pobjcl.h newcmdcl.h ../pobjcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../optioncl.h setcl.h cmdutil.h \
  ../sim.src/uccl.h
timer.o: timer.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
  ../sim.src/simcl.h ../pobjcl.h ../pobjt.h ../eventcl.h newcmdcl.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h timercl.h
bp.o: bp.cc ../ddconfig.h ../sim.src/brkcl.h ../ddconfig.h ../pobjcl.h \
  ../ddconfig.h ../pobjt.h ../eventcl.h ../stypes.h ../sim.src/memcl.h \
  ../sim.src/guiobjcl.h ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h \
  ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h cmdsetcl.h bpcl.h
info.o: info.cc ../i_string.h ../ddconfig.h ../sim.src/simcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h infocl.h
show.o: show.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h ../errorcl.h \
  ../sim.src/simcl.h showcl.h
cmdgui.o: cmdgui.cc ../ddconfig.h ../globals.h ../ddconfig.h ../stypes.h \
  ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h \
  ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
  newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/simcl.h cmdguicl.h
cmdconf.o: cmdconf.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h commandcl.h newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h \
  ../sim.src/simcl.h cmdconfcl.h
cmduc.o: cmduc.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h commandcl.h newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h \
  ../sim.src/uccl.h cmduccl.h
cmdstat.o: cmdstat.cc ../ddconfig.h ../globals.h ../ddconfig.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../sim.src/simcl.h cmdstatcl.h
cmdmem.o: cmdmem.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h commandcl.h newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h \
  ../sim.src/simcl.h cmdmemcl.h
newcmd.o: newcmd.cc ../ddconfig.h ../i_string.h ../ddconfig.h cmdlexcl.h \
  ../globals.h ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h ../sim.src/simcl.h \
  ../sim.src/argcl.h cmdutil.h ../sim.src/uccl.h
newcmdposix.o: newcmdposix.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
  ../globals.h ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../pobjcl.h ../appcl.h commandcl.h \
  newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../utils.h ../sim.src/simcl.h \
  ../sim.src/argcl.h newcmdposixcl.h cmdutil.h ../sim.src/uccl.h
cmdpars.o: cmdpars.cc cmdlexcl.h ../sim.src/memcl.h ../ddconfig.h \
  ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/guiobjcl.h ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h \
  ../globals.h ../appcl.h ../optioncl.h ../sim.src/argcl.h \
  ../sim.src/simcl.h newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  commandcl.h newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/memcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h ../stypes.h
cmdlex.o: cmdlex.cc cmdlexcl.h cmdpars.hh ../globals.h ../ddconfig.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  commandcl.h newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h
