arg.o: arg.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h simcl.h ../gui.src/ifcl.h guiobjcl.h \
  ../ddconfig.h uccl.h hwcl.h guiobjcl.h memcl.h ../eventcl.h \
  ../errorcl.h brkcl.h stackcl.h argcl.h simcl.h ../cmd.src/cmdutil.h \
  uccl.h argcl.h
brk.o: brk.cc ../ddconfig.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
  ../eventcl.h brkcl.h ../stypes.h memcl.h guiobjcl.h ../eventcl.h \
  ../errorcl.h ../pobjcl.h ../stypes.h
guiobj.o: guiobj.cc guiobjcl.h ../ddconfig.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h
hw.o: hw.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../stypes.h hwcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h guiobjcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h \
  ../stypes.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  simcl.h ../gui.src/ifcl.h guiobjcl.h uccl.h hwcl.h memcl.h \
  ../ddconfig.h guiobjcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h \
  argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h memcl.h uccl.h
itsrc.o: itsrc.cc ../ddconfig.h ../i_string.h ../ddconfig.h itsrccl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../stypes.h
mem.o: mem.cc ../i_string.h ../ddconfig.h ../utils.h ../stypes.h \
  ../globals.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h simcl.h ../gui.src/ifcl.h guiobjcl.h \
  ../ddconfig.h uccl.h hwcl.h guiobjcl.h memcl.h ../eventcl.h \
  ../errorcl.h brkcl.h stackcl.h argcl.h simcl.h ../cmd.src/newcmdcl.h \
  ../cmd.src/cmdutil.h uccl.h memcl.h hwcl.h
obsolete.o: obsolete.cc
sim.o: sim.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h simcl.h ../gui.src/ifcl.h guiobjcl.h \
  ../ddconfig.h uccl.h hwcl.h guiobjcl.h memcl.h ../eventcl.h \
  ../errorcl.h brkcl.h stackcl.h argcl.h ../cmd.src/cmdsetcl.h \
  ../cmd.src/cmdguicl.h simcl.h ../appcl.h
stack.o: stack.cc ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h \
  ../ddconfig.h ../pobjt.h ../eventcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  simcl.h ../gui.src/ifcl.h guiobjcl.h ../ddconfig.h uccl.h hwcl.h \
  guiobjcl.h memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h argcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h stackcl.h
test_mem_speed.o: test_mem_speed.cc memcl.h ../ddconfig.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h guiobjcl.h \
  ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h hwcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  simcl.h ../gui.src/ifcl.h guiobjcl.h uccl.h hwcl.h memcl.h brkcl.h \
  ../ddconfig.h stackcl.h ../errorcl.h argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h uccl.h
uc.o: uc.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h simcl.h ../gui.src/ifcl.h guiobjcl.h \
  ../ddconfig.h uccl.h hwcl.h guiobjcl.h memcl.h ../eventcl.h \
  ../errorcl.h brkcl.h stackcl.h argcl.h ../utils.h ../cmd.src/newcmdcl.h \
  ../cmd.src/cmduccl.h ../cmd.src/bpcl.h ../cmd.src/getcl.h \
  ../cmd.src/setcl.h ../cmd.src/infocl.h ../cmd.src/timercl.h \
  ../cmd.src/cmdstatcl.h ../cmd.src/cmdmemcl.h ../cmd.src/cmdutil.h \
  uccl.h uccl.h hwcl.h memcl.h simcl.h itsrccl.h ../pobjcl.h ../stypes.h
