glob.o: glob.cc ../stypes.h ../ddconfig.h
hc08.o: hc08.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  hc08cl.h ../sim.src/uccl.h regshc08.h instcl.h glob.h ../stypes.h \
  hc08mac.h
inst.o: inst.cc ../ddconfig.h hc08cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regshc08.h instcl.h hc08mac.h
shc08.o: shc08.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../appcl.h simhc08cl.h \
  ../sim.src/simcl.h
simhc08.o: simhc08.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h simhc08cl.h ../sim.src/simcl.h \
  hc08cl.h ../sim.src/uccl.h regshc08.h ../ddconfig.h instcl.h
