glob.o: glob.cc ../stypes.h ../ddconfig.h
glob_lr35902.o: glob_lr35902.cc ../stypes.h ../ddconfig.h
glob_r2k.o: glob_r2k.cc glob.cc ../stypes.h ../ddconfig.h
inst_cb.o: inst_cb.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h
inst.o: inst.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h
inst_ddcb.o: inst_ddcb.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h inst_xxcb.cc
inst_dd.o: inst_dd.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h \
  inst_xd.cc
inst_ed.o: inst_ed.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h
inst_ed_r2k.o: inst_ed_r2k.cc ../ddconfig.h r2kcl.h z80cl.h \
  ../sim.src/uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
  ../eventcl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h
inst_fdcb.o: inst_fdcb.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h inst_xxcb.cc
inst_fd.o: inst_fd.cc ../ddconfig.h z80cl.h ../sim.src/uccl.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h \
  inst_xd.cc
inst_lr35902.o: inst_lr35902.cc ../ddconfig.h lr35902cl.h z80cl.h \
  ../sim.src/uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
  ../eventcl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h
inst_r2k.o: inst_r2k.cc ../ddconfig.h r2kcl.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h
inst_xd.o: inst_xd.cc
inst_xxcb.o: inst_xxcb.cc
lr35902.o: lr35902.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  z80cl.h ../sim.src/uccl.h regsz80.h instcl.h lr35902cl.h glob.h \
  ../stypes.h
r2k.o: r2k.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  z80cl.h ../sim.src/uccl.h regsz80.h instcl.h r2kcl.h glob.h ../stypes.h
simz80.o: simz80.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h simz80cl.h ../sim.src/simcl.h \
  z80cl.h ../sim.src/uccl.h regsz80.h ../ddconfig.h instcl.h r2kcl.h \
  lr35902cl.h
sz80.o: sz80.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
  ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h \
  ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../sim.src/argcl.h ../appcl.h simz80cl.h \
  ../sim.src/simcl.h
z80.o: z80.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  z80cl.h ../sim.src/uccl.h regsz80.h instcl.h glob.h ../stypes.h
