arith.o: arith.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h types51.h
bit.o: bit.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
  ../eventcl.h ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h \
  ../stypes.h ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h types51.h
glob.o: glob.cc ../stypes.h ../ddconfig.h
inc.o: inc.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
  ../eventcl.h ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h \
  ../stypes.h ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h
interrupt.o: interrupt.cc ../utils.h ../stypes.h ../ddconfig.h \
  ../sim.src/itsrccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../stypes.h \
  interruptcl.h ../stypes.h ../pobjcl.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/argcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../sim.src/memcl.h \
  ../eventcl.h ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
  ../cmd.src/newcmdcl.h regs51.h types51.h ../ddconfig.h
jmp.o: jmp.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
  ../eventcl.h ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h \
  ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h \
  ../stypes.h ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h types51.h
logic.o: logic.cc ../ddconfig.h ../stypes.h ../ddconfig.h uc51cl.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h interruptcl.h ../cmd.src/newcmdcl.h regs51.h
mov.o: mov.cc ../ddconfig.h ../sim.src/memcl.h ../ddconfig.h ../stypes.h \
  ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/guiobjcl.h \
  ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h uc51cl.h ../pobjcl.h \
  ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h \
  ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/memcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
  ../sim.src/argcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h
pca.o: pca.cc ../sim.src/itsrccl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
  ../eventcl.h ../stypes.h pcacl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h regs51.h types51.h \
  ../ddconfig.h
port.o: port.cc portcl.h ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
  ../eventcl.h ../sim.src/uccl.h ../stypes.h ../pobjcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../cmd.src/newcmdcl.h regs51.h types51.h \
  ../ddconfig.h
s51.o: s51.cc ../ddconfig.h ../globals.h ../ddconfig.h ../stypes.h \
  ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h \
  ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h ../appcl.h \
  sim51cl.h ../sim.src/simcl.h
serial.o: serial.cc ../ddconfig.h ../globals.h ../ddconfig.h ../stypes.h \
  ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h \
  ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h serialcl.h \
  ../stypes.h ../pobjcl.h ../sim.src/uccl.h regs51.h uc51cl.h \
  ../sim.src/simcl.h ../sim.src/memcl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h interruptcl.h ../cmd.src/newcmdcl.h \
  ../cmd.src/cmdutil.h ../sim.src/uccl.h
sim51.o: sim51.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
  ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h \
  ../appcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../utils.h ../cmd.src/cmdutil.h ../sim.src/uccl.h sim51cl.h \
  ../sim.src/simcl.h uc51cl.h ../pobjcl.h ../sim.src/memcl.h \
  ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h ../stypes.h \
  interruptcl.h ../cmd.src/newcmdcl.h uc52cl.h uc51rcl.h uc89c51rcl.h \
  uc251cl.h uc390cl.h glob.h
timer0.o: timer0.cc timer0cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/uccl.h ../stypes.h ../pobjcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../cmd.src/newcmdcl.h uc51cl.h ../sim.src/simcl.h \
  ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h \
  interruptcl.h regs51.h types51.h ../ddconfig.h
timer1.o: timer1.cc timer1cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/uccl.h ../stypes.h ../pobjcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../cmd.src/newcmdcl.h timer0cl.h uc51cl.h \
  ../sim.src/simcl.h ../sim.src/memcl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h interruptcl.h regs51.h
timer2.o: timer2.cc timer2cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/uccl.h ../stypes.h ../pobjcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h ../cmd.src/newcmdcl.h timer0cl.h uc51cl.h \
  ../sim.src/simcl.h ../sim.src/memcl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h interruptcl.h regs51.h types51.h ../ddconfig.h
uc251.o: uc251.cc ../ddconfig.h uc251cl.h uc89c51rcl.h uc51rcl.h uc52cl.h \
  uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h \
  ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h
uc390.o: uc390.cc ../ddconfig.h ../i_string.h ../ddconfig.h glob.h \
  uc390cl.h uc52cl.h uc51cl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h uc390hwcl.h timer2cl.h timer0cl.h
uc390hw.o: uc390hw.cc ../ddconfig.h uc390hwcl.h ../sim.src/uccl.h \
  ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h uc390cl.h uc52cl.h uc51cl.h ../pobjcl.h \
  ../sim.src/simcl.h ../sim.src/memcl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h
uc51.o: uc51.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../utils.h \
  ../stypes.h ../globals.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h \
  ../appcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../optioncl.h ../cmd.src/cmduccl.h uc51cl.h ../pobjcl.h \
  ../sim.src/simcl.h ../sim.src/memcl.h ../sim.src/uccl.h \
  ../sim.src/itsrccl.h ../sim.src/brkcl.h ../stypes.h interruptcl.h \
  ../cmd.src/newcmdcl.h glob.h regs51.h timer0cl.h timer1cl.h serialcl.h \
  portcl.h types51.h
uc51r.o: uc51r.cc ../ddconfig.h uc51rcl.h uc52cl.h uc51cl.h ../pobjcl.h \
  ../ddconfig.h ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h types51.h wdtcl.h
uc52.o: uc52.cc ../ddconfig.h uc52cl.h uc51cl.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../pobjcl.h \
  ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h ../appcl.h ../pobjcl.h \
  ../optioncl.h ../stypes.h ../sim.src/argcl.h ../stypes.h \
  ../sim.src/simcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h timer2cl.h timer0cl.h
uc89c51r.o: uc89c51r.cc ../ddconfig.h uc89c51rcl.h uc51rcl.h uc52cl.h \
  uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h \
  ../sim.src/simcl.h ../pobjcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h \
  ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
  ../ddconfig.h ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h \
  ../sim.src/memcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
  ../sim.src/brkcl.h ../stypes.h interruptcl.h ../cmd.src/newcmdcl.h \
  regs51.h pcacl.h wdtcl.h
wdt.o: wdt.cc wdtcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
  ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../ddconfig.h \
  ../pobjcl.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h ../ddconfig.h \
  ../pobjcl.h ../sim.src/simcl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
  ../sim.src/brkcl.h ../sim.src/stackcl.h uc51rcl.h ../ddconfig.h \
  uc52cl.h uc51cl.h ../pobjcl.h ../sim.src/simcl.h ../sim.src/memcl.h \
  ../sim.src/itsrccl.h ../sim.src/brkcl.h ../stypes.h interruptcl.h \
  ../cmd.src/newcmdcl.h regs51.h
