SDCChasht.o: SDCChasht.c SDCCerr.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCChasht.h ../support/util/newalloc.h
SDCCset.o: SDCCset.c ../support/util/newalloc.h SDCCerr.h SDCCset.h
SDCCutil.o: SDCCutil.c ../support/util/dbuf.h SDCCglobl.h SDCCset.h \
 ../sdccconf.h SDCCerr.h SDCCmacro.h SDCChasht.h SDCCutil.h \
 ../support/util/newalloc.h ../support/util/dbuf_string.h \
 ../support/util/dbuf.h version.h
SDCCerr.o: SDCCerr.c SDCCerr.h
SDCCsystem.o: SDCCsystem.c SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h \
 SDCCutil.h SDCChasht.h ../support/util/dbuf.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h SDCCsystem.h \
 ../support/util/newalloc.h
NewAlloc.o: ../support/util/NewAlloc.c ../support/util/newalloc.h
dbuf.o: ../support/util/dbuf.c ../support/util/dbuf.h
dbuf_string.o: ../support/util/dbuf_string.c \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
findme.o: ../support/util/findme.c ../support/util/system.h \
 ../support/util/findme.h
SDCCnaddr.o: SDCCnaddr.cc SDCCnaddr.hpp SDCCtree_dec.hpp SDCCsymt.h \
 SDCChasht.h SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h \
 ../support/util/dbuf.h SDCCval.h SDCCicode.h SDCCbitv.h SDCCBBlock.h \
 SDCCopt.h SDCCy.h
